org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraftVersion=26.1.2
neoForgeVersion=26.1.2.104

# Dependencies
resourcefulLibVersion=4.0.1
olympusVersion=1.8.4

# Optional dependencies
resourcefulConfigVersion=4.0.1
openPartiesAndClaimsVersion=0.31.6
jeiVersion=29.43.0.104
architecturyVersion=20.0.6
reiVersion=26.1.819

modVersion=1.1.0
modGroup=me.johardt.theseus
