org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraftVersion=26.2
neoForgeVersion=26.2.0.86

# Dependencies
resourcefulLibVersion=5.0.4
olympusVersion=1.9.4

# Optional dependencies
resourcefulConfigVersion=5.0.0
openPartiesAndClaimsVersion=0.31.6
jeiVersion=30.32.0.221
architecturyVersion=21.0.7
reiVersion=26.2.821

modVersion=1.1.0
modGroup=me.johardt.theseus
